### ISSUE TITLE
[MMM:Ship]Feature: Too many minions spawn by default

### ISSUE THREAD

**Issue by ghost** [joseffaghihi/GamificationAlgebraConcepts#8]
When the game starts, the minions will start spawning sporadically.  Instead, there should be a implementation of 'waves'.
0 = Tutorial \ Slowest
1 = Slow
2 = Below Normal
3 = Normal
4 = Above Normal
5 = High

Any thoughts?

**Comment by joseffaghihi** [comment]
Are not these just the speed to which minion's get instantiated in the scene according to the players performance ? that is clicking speed and  the number of right or wrong clicks?

**Comment by Davidizm** [comment]
I still think there should be the one minion, and then until he gets destroyed, the two minions, and then when he gets destroyed, three for a few rounds. and then waves.

Date: Mon, 25 May 2015 00:48:58 -0700

**Comment by joseffaghihi** [comment]
I think I misunderstood what you have said. Can you please explain this on Saturday?
Sorry for that.
Thanks,

**Comment by Davidizm** [comment]
yes

Date: Tue, 26 May 2015 08:39:19 -0700

**Comment by joseffaghihi** [comment]
Next changes to Minions:

1) When the scene is very crowded it is not clear which number was the answer. Sometimes when the right and wrong numbers get to the top, you get the message "Correct".

2) There is no =0 in the formula

3) sometime the formula needs to be changes 2x^2 + 4x+5 =0 , after two or three times the formula will change like -4x^2= -4x+5 , now if you ask what is B the user must be able to know -4 is not the answer and 4 is the answer.

This will give dynamic to the program.

4) when the user can not get the answer after three times the TUTORIAL with David's voice will reappear. 

5 ) Now in 2x^2 + 4x+5 =0 , User may get a, b and c  correctly but when it comes to  -4x^2= -4x+5, the user may make mistake. So we need to create a tutorial for this type problem.

6) When user gets the right or wrong answer, the number flies to the formula. To visually show the user what is going on, the number attract by the formula. if it is true it goes to its place in the formula otherwise visually we show that the number can not be attracted by the formula (I can explain this on our Skype call).

**Comment by joseffaghihi** [comment]
Nicholas:I have to remember how to implement the wave system and minion speed throttle.

**Comment by ghost** [comment]
Currently working on this...

**Comment by ghost** [comment]
Added a very primitive version has just been submitted.  Is there any further ideas as to how it should work?

Also, is there any further input with Davidizm's thoughts on this [ https://github.com/joseffaghihi/GamificationAlgebraConcepts/issues/8#issuecomment-105536273 ]?

**Comment by ghost** [comment]
This topic has been shifted towards the User Performance AI.
https://github.com/joseffaghihi/GamificationAlgebraConcepts/issues/13
